#!/usr/bin/env python3
"""
Draw the homepage record curve: cumulative granted patents, 2011 to 2026.

`design.md` says the record is drawn, not tabulated, and that a third drawn
record must use a NEW positional encoding rather than a fourth mark treatment.
/patents/ owns discrete year columns and /research/ owns lanes across time, so
this one is a continuous cumulative line: it carries the accumulation rate,
which a per-year histogram cannot show, and it lands on exactly 358.

Two deliberate choices worth knowing before editing:

1. The SVG carries no text. Text inside a viewBox scales with the graphic, so
   an 11px label would render near 4px once the curve is 350px wide, straight
   through the documented type floor. Every label is HTML, at real token sizes.
2. preserveAspectRatio is "none" so the curve fills whatever box it is given,
   with non-scaling strokes so the hairlines keep their weight. That is also
   why there is no end dot: a circle would render as an ellipse.

The SVG is written into index.html between marker comments so the curve cannot
drift from the data. Re-run this whenever _gen/patents.py rebuilds the JSON.
Never hand-edit the block it writes.

    python3 _gen/record_curve.py
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "assets", "data", "patents.json")
PAGE = os.path.join(ROOT, "index.html")

START = "<!-- RECORD-CURVE:START generated by _gen/record_curve.py, do not hand-edit -->"
END = "<!-- RECORD-CURVE:END -->"

# Plot box in user units. Baseline at zero, peak at the top inset. No gridlines:
# the only rule on the chart is the baseline, per design.md's chart list.
W, TOP, BASE = 1000, 4, 96


def main():
    with open(DATA, encoding="utf-8") as f:
        data = json.load(f)

    hist = data["hist"]                      # [[year, grants], ...]
    granted = data["counts"]["granted"]
    in_force = data["counts"]["inForce"]

    # Cumulative series. The last value must equal the published grant count,
    # otherwise the curve and the stat rail would tell the reader two things.
    total = 0
    series = []
    for year, n in hist:
        total += n
        series.append((year, total))
    if total != granted:
        raise SystemExit(
            "refusing to draw: cumulative total %d does not equal granted %d. "
            "The curve may never state a figure the record does not."
            % (total, granted)
        )

    first_year, first_val = series[0]
    last_year, last_val = series[-1]

    step = W / (len(series) - 1)
    scale = (BASE - TOP) / last_val
    pts = [(i * step, BASE - v * scale) for i, (_, v) in enumerate(series)]

    # The final year is still running, so its count is a fraction of a full
    # year and the curve visibly flattens at the right edge. Drawn solid that
    # reads as output slowing down, which the data does not say. The last
    # segment is dashed and labelled "to date" so the flattening is read as an
    # incomplete year rather than a decline.
    solid = " ".join("%.1f,%.1f" % q for q in pts[:-1])
    partial = " ".join("%.1f,%.1f" % q for q in pts[-2:])
    part_n = series[-1][1] - series[-2][1]
    years = len(series)

    desc = (
        "A line rising from %d grant in %d to %d by %d, %d of them still in "
        "force, across %d consecutive years. The final segment is dashed "
        "because %d is still running, with %d grants so far. The same figures "
        "are listed below."
        % (first_val, first_year, last_val, last_year, in_force, years,
           last_year, part_n)
    )

    svg = f"""{START}
    <figure class="record-curve">
      <p class="rc-val"><strong>{last_val}</strong> granted</p>
      <svg viewBox="0 0 {W} {BASE}" preserveAspectRatio="none" role="img"
           aria-labelledby="rc-title rc-desc" focusable="false">
        <title id="rc-title">Granted U.S. patents, cumulative</title>
        <desc id="rc-desc">{desc}</desc>
        <polyline class="rc-line" points="{solid}" vector-effect="non-scaling-stroke" />
        <polyline class="rc-line rc-line--partial" points="{partial}" vector-effect="non-scaling-stroke" />
        <line class="rc-base" x1="0" y1="{BASE}" x2="{W}" y2="{BASE}"
              vector-effect="non-scaling-stroke" />
      </svg>
      <p class="rc-axis"><span>{first_year}</span><span>{last_year} to date</span></p>
      <figcaption class="caption">
        Granted U.S. patents, cumulative. {years} consecutive years with a grant,
        {first_val} in {first_year} to {last_val} by {last_year}, {in_force} still
        in force. The dashed segment is {last_year}, still running at {part_n}.
      </figcaption>
    </figure>
    {END}"""

    with open(PAGE, encoding="utf-8") as f:
        page = f.read()

    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if not pattern.search(page):
        raise SystemExit(
            "markers not found in index.html. Add the START/END pair inside "
            "the record section before running this."
        )
    page = pattern.sub(lambda _: svg, page)

    with open(PAGE, "w", encoding="utf-8") as f:
        f.write(page)

    print("wrote the record curve: %d points, %d to %d, ending at %d, %d in force"
          % (len(series), first_year, last_year, last_val, in_force))


if __name__ == "__main__":
    main()
